### ISSUE TITLE
force double quotation option

### ISSUE THREAD

**Issue by sue445** [sue445/heart_seed#15]
## now

``` yaml
articles_1:
  id: 1
  title: title1
  description: description1
  created_at: '2014-06-01 12:10:00 +0900'
```
## feture

``` yaml
articles_1:
  id: 1
  title: "title1"
  description: "description1"
  created_at: '2014-06-01 12:10:00 +0900'
```
